events {
    # Basic event configuration (required even if empty)
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name _;
    
        root /usr/share/nginx/html;
    
        location / {
            autoindex on;
        }
    
        location /boot/ {
            autoindex on;
        }
    
        location /autoinstall/ {
            autoindex on;
        }
    }
}
