@startuml
top to bottom direction
namespace ansible {
    class "AnsibleJSONResults" << (S,Aquamarine) >> {
        + Plays []<font color=blue>struct</font>{[]<font color=blue>struct</font>{<font color=blue>map</font>[string]<font color=blue>struct</font>{<font color=blue>interface</font>{}}}}

    }
    class "K3sConfig" << (S,Aquamarine) >> {
        + ServerIP string
        + DisableComponents string
        + CPUManagerPolicy string
        + SystemReservedCPU string
        + KubeReservedCPU string
        + SystemReservedMem string
        + KubeReservedMem string

    }
    class "K3sCreds" << (S,Aquamarine) >> {
        + Server string
        + Token string

    }
    class "template" << (S,Aquamarine) >> {
        - machineType string

    }
}




@enduml
