@startuml
top to bottom direction
namespace http {
    class "HTTPError" << (S,Aquamarine) >> {
        + Error string
        + Message string

    }
    class "pipeLine" << (S,Aquamarine) >> {
        + Name string
        + Mac string
        + IP string
        + OS string

    }
}




@enduml
