@startuml
top to bottom direction
namespace kubernetes {
    class "Client" << (S,Aquamarine) >> {
        - cs kubernetes.Interface

        + ClusterInfo(ctx context.Context) (*ClusterInfo, error)
        + Nodes(ctx context.Context) ([]NodeInfo, error)
        + Node(ctx context.Context, name string) (*NodeInfo, error)
        + Pods(ctx context.Context, namespace string) ([]PodInfo, error)
        + Services(ctx context.Context, namespace string) ([]ServiceInfo, error)
        + Events(ctx context.Context, namespace string) ([]EventInfo, error)

    }
    class "Cluster" << (S,Aquamarine) >> {
        + ID string
        + KubeConfig string
        + Token string
        + APIEndpoint string
        + Info *ClusterInfo
        + Ready bool
        + Nodes []<font color=blue>struct</font>{string, string, string, string}

    }
    class "ClusterInfo" << (S,Aquamarine) >> {
        + ClusterID string
        + NodeCount int
        + Namespaces []string
        + ServerVersion string
        + Events []EventInfo
        + Pods []PodInfo
        + Nodes []NodeInfo

    }
    class "Clusters" << (S,Aquamarine) >> {
        + Cluster <font color=blue>map</font>[string]*Cluster

    }
    class "EventInfo" << (S,Aquamarine) >> {
        + Namespace string
        + Name string
        + Reason string
        + Message string
        + Count int32
        + Type string

    }
    class "NodeInfo" << (S,Aquamarine) >> {
        + Name string
        + Status string
        + Roles []string
        + OS string
        + KernelVersion string
        + ContainerRuntime string
        + Architecture string
        + CPUCapacity string
        + MemoryCapacity string
        + CPUAllocatable string
        + MemoryAllocatable string
        + InternalIP string
        + Labels <font color=blue>map</font>[string]string

    }
    class "PodInfo" << (S,Aquamarine) >> {
        + Name string
        + Namespace string
        + Status string
        + Node string
        + IP string
        + Images []string

    }
    class "ServiceInfo" << (S,Aquamarine) >> {
        + Name string
        + Namespace string
        + Type string
        + ClusterIP string
        + Ports []string

    }
}


"kubernetes.Cluster""uses" o-- "kubernetes.ClusterInfo"
"kubernetes.ClusterInfo""uses" o-- "kubernetes.EventInfo"
"kubernetes.ClusterInfo""uses" o-- "kubernetes.NodeInfo"
"kubernetes.ClusterInfo""uses" o-- "kubernetes.PodInfo"
"kubernetes.Clusters""uses" o-- "kubernetes.Cluster"


@enduml
